### ISSUE TITLE
O10N_DISABLED does not work

### ISSUE THREAD

**Issue by AlphaDE** [o10n-x/wordpress-html-optimization#4]
Due to a problem with a plugin, I noticed that 

define('O10N_DISABLED', true);

does not show the required effect. Disabling the plugin via plugin manager makes the event plugin in question to work in the backend, by disabling via O10N_DISABLED, the plugin does not.

So despite that setting, the html optimization plugin seems to do something.

**Comment by optimalisatie** [comment]
At what position did you set `define('O10N_DISABLED', true);`?

The plugin simply disables itself on setup. When disabled, it doesn't hook to the output buffer and thus will not touch HTML.

The admin however, will continue to function. The disabled setting has no effect on the plugin admin.

```php
/**
 * Setup controller
 */
protected function setup()
{
    // disabled
    if (!$this->env->enabled('html')) {
        return;
    }

    // ...
}
```

**Comment by AlphaDE** [comment]
At the end of wp_config.php, where it works for conditions, too. I even put a unconditional global define(O10N_DISBALED,true); in.
But nevertheless, as long as the plugin is not fully deactivated, it breaks my event manager plugin on the backend. After changing the html minifier, the event plugin did work.

But that shows that the html plugin is running on the backend, despite O10N_DISABLED is set to true.

**Comment by optimalisatie** [comment]
Is the HTML source minified despite `O10N_DISABLED` being set to true?

It simply should not be possible. The `env->enabled()` check returns false when `O10N_DISABLED` is set to true. There should be no possibility for the HTML optimization to hook into the output buffer, thus it should be completely disabled.

All optimization plugins use the same (a single) output buffer, `str_replace` and `preg_replace` hooks for optimal performance. When disabled, the plugin is simply not attached to the relevant WordPress filter hooks and thus it will not do anything and not cause any overhead from being present.

```php
// global disabled
if (defined('O10N_DISABLED') && O10N_DISABLED) {
    return $this->enabled = false;
}
```

Could you please verify if `O10N_DISABLED` is indeed set using `functions.php`?

```php
# test if O10N_DISABLED is defined (use query string /?test)
if (isset($_GET['test'])) {
    if (defined('O10N_DISABLED')) {
        wp_die('O10N_DISABLED defined, value: ' . ((O10N_DISABLED) ? 'true' : 'false') );
    } else {
        wp_die('O10N_DISABLED not defined');
    }
}
```

**Comment by AlphaDE** [comment]
I'll try that later... the insrallation in question is on another server where access is a bit more complicate than on my own server.

The event plugin is "All-in-One Event Calendar by Time.ly"

The backend to setup an event was not working anymore. I assumed an optimization problem and first amended

if (strpos($_SERVER["REQUEST_URI"],"/wp-admin/") !== false) {
    define('O10N_DISABLED', true);
}

at the end of wp_config.php.

It's at the same position where I put the disable-statements for AMP-pages (and they did work).

But nothing happened. So I started to disable the O10N plugins and determined it was the html optimization. I even put in an unconditional define('O10N_DISABLED', true); but the problem persisted. 

The backend part of the events plugin worked when I disabled html optimization completely.

And after changing the minifier from Minify to HtmlMin, the event backend worked.

Btw did you see the issue on the Net_URL2 rebase?

**Comment by AlphaDE** [comment]
I put a single

    define('O10N_DISABLED', true);

at the end of wp_config.php and get

O10N_DISABLED not defined

on /?test

**Comment by optimalisatie** [comment]
It means that for some reason the `wp-config.php` that you modified isn't used by the WordPress installation. PHP constants can't be unset or modified after they are defined (it could be done but would require a [PECL extension](http://php.net/manual/en/function.runkit-constant-remove.php)).

The plugin `All-in-One Event Calendar by Time.ly` is in use on the website of one of our customers and is working well with the default HTML minifier.

**Comment by AlphaDE** [comment]
Conclusion so far... for the backend to work, the define must be before

```
/* That's all, stop editing! Happy blogging. */

/** Absolute path to the WordPress directory. */
if ( !defined('ABSPATH') )
	define('ABSPATH', dirname(__FILE__) . '/');

/** Sets up WordPress vars and included files. */
require_once(ABSPATH . 'wp-settings.php');

```

Then the define does show effect. The plugin does work on the frontend, but the the minify html minifier, it breaks the event editor on the backend.

**Comment by optimalisatie** [comment]
`/* That's all, stop editing! Happy blogging. */` provides guidance by WordPress.

`wp-config.php` is not simply a configuration data holder, it actually initiates the complete WordPress installation by loading `wp-settings.php`. Configuration should be defined before WordPress is initiated.

In order to test a `REQUEST_URI` match, you could use the previous test snippet that I provided.

```php
# test strpos matching
if (isset($_GET['test'])) {

    // test string
    $str = '/wp-admin/';

    wp_die('REQUEST_URI: '.$_SERVER['REQUEST_URI'].'<br />
Test string: '.$str.'<br />
strpos match result: ' . ((strpos($_SERVER['REQUEST_URI'], $str) !== false) ? 'true' : 'false'));
}
```

**Comment by AlphaDE** [comment]
Learned something new, thx Jan.
